### ISSUE TITLE
Add option to log "Dependency Lookup Failure"s as errors

### ISSUE THREAD

**Issue by JordanJLopez** [mend/renovate-on-prem#100]
**Which Renovate are you using?**

Renovate Pro v0.18.5

**Which platform are you using?**

Enterprise GitHub

**Have you checked the logs? Don't forget to include them if relevant**

Yes

```
INFO: Dependency lookup failure: unauthorized (repository=${MY_ORG}/${MY_REPO})
       "pkgUrl": "${CORPORATE_ARTYLAB_LINK}",
       "authInfoType": "Basic",
       . . .
       "statusCode": 403,
       "statusMessage": "Forbidden",
       . . .
```

**What would you like to do?**

I believe dependency lookup failures should be logged as `ERROR` rather than as `INFO`, at least for certain responses from package sources like `403 Forbidden`.

**Comment by rarkins** [comment]
Depends on https://github.com/renovatebot/renovate/issues/5557

**Comment by rarkins** [comment]
This needs to be a feature request in the main Renovate repo as it isn't on-prem specific.
