### ISSUE TITLE
EACCES: permission denied, mkdir '/tmp/renovate'

### ISSUE THREAD

**Issue by janpio** [mend/renovate-on-prem#143]
Using the [GH Docker Compose file example](https://github.com/whitesource/renovate-on-prem/blob/master/examples/docker-compose-ghe.yml) with:

```
    volumes:
      - "/tmp/renovate/:/tmp/" # Use a volume for this as the cache will cause a lot of churn
Terms
```

... I get the following error when Renovate is actually trying to process something:

```
renovate_1  | ERROR: renovateRepository error (repository=prisma/prisma-renovate)
renovate_1  |        "err": {
renovate_1  |          "errno": -13,
renovate_1  |          "code": "EACCES",
renovate_1  |          "syscall": "mkdir",
renovate_1  |          "path": "/tmp/renovate",
renovate_1  |          "message": "EACCES: permission denied, mkdir '/tmp/renovate'",
renovate_1  |          "stack": "Error: EACCES: permission denied, mkdir '/tmp/renovate'"
renovate_1  |        }
```

`docker-compose up` is called via user `root`, the folder also already exists on the host:
```
root@prisma-renovate-docker-ubuntu-s-1vcpu-1gb-sfo3-01:/tmp# ls -l
total 20
drwxr-xr-x 2 root root 4096 Mar 18 17:16 renovate
```

Probably something really basic but I can't figure it out right now.

**Comment by wiget** [comment]
As this is `/tmp` in container permissions should be the same as `/tmp` on host. Alternatively you can change folder's uid to 1000 (if I remember correctly this uid is used by user in container)

**Comment by rarkins** [comment]
Can you make sure to pull `whitesource/renovate:1.3.0` again, in case the SHA has changed? The first time the image was created it was missing the `USER 1000` at the end of the Dockerfile.

Assuming you are running the image as user 1000 (ubuntu), that directory needs to be writeable by ubuntu. I don't recall anything special I've needed to do in the past for that to happen.

What's your host type (e.g. Ubuntu?) and what's the ownership of `/tmp/renovate` right now? Maybe remove and re-add it with user 1000 permissions?

**Comment by janpio** [comment]
You overestimate my knowledge and understanding of what I am doing ;) But I think I figured it out:

This is a Digitalocean Droplet running Ubuntu with Docker installed, I was logged in as `root`. I now deleted `/tmp/renovate` again, created a new user `ubuntu`, added it to the `docker` group, switched to that user, and ran `docker-compose up` as that user. This seems to make it work:

```
rm -r /tmp/renovate
adduser ubuntu
sudo usermod -aG docker ubuntu
newgrp docker 
usermod -aG sudo ubuntu
sudo ubuntu
# checkout repo again
docker-compose up
```

**Comment by rarkins** [comment]
You seem to be doing fine with the knowledge you have :)

I think it's best that you create `ubuntu` as you've done, but I also think it is a permissions issue not directly *user id*. In other words, running from root could work but only if the folders it shares into the container are write-enabled for user 1000. One way to do that would be to make it chmod 777, although that's generally not a best practice either.

There is also a [dockerUser](https://docs.renovatebot.com/self-hosted-configuration/#dockeruser) admin option addressing a similar challenge but I've never needed it as I use user `ubuntu`/1000 myself.

**Comment by Byh0ki** [comment]
Hello,

I have the same issue on a GKE cluster, the volume is mounted with root ownership so renovate (running as Ubuntu/1000 user) is not able to use the cache directory and crashes.

I've quick fixed it on my instance using a `initContainer` to perform a `chown -R 1000:1000 /tmp/renovate` before renovate is started, this fixed it. I'll will likely open a PR to add support for `initContainers` in the chart

**Comment by agaudreault-jive** [comment]
You can solve this by configuring the helm chart with `fsGroup`. See [Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods) documentation.

```yaml
  renovate:
    podSecurityContext:
      fsGroup: 1000

    cachePersistence:
      enabled: true
      size: 10Gi
```
