### ISSUE TITLE
Renovate started to create a lot of PRs after upgrade

### ISSUE THREAD

**Issue by vladh91** [mend/renovate-on-prem#238]
Hey guys,
We have upgraded our Renovate deployment fom v1.3.1 to v2.6.0. After the upgrade we are seeing a lot of PR's created even if we provide `prCommitsPerRunLimit: 5,`  in config.js.

**Comment by rarkins** [comment]
That option doesn't really apply to renovate on prem because it's always running. I'm not sure if/how it worked before

**Comment by vladh91** [comment]
Hey @rarkins, thanks for the response. Is there any way to limit number of the requests since with this we will have really big load coming to our GitLab?

**Comment by vladh91** [comment]
Helm chart does support `config` section which is related to renovate configuration itself and lot of sections are working properly. Also https://docs.renovatebot.com/self-hosted-configuration/#prcommitsperrunlimit per this renovate should support it. Logically I was thinking that since we have `schedulerCron` setup it will generate up to 5 PR's on each Renovate Run per schedule.

**Comment by vladh91** [comment]
Additionally if I downgrade renovate to 1.3.1 version the behavior of creating lot of PR's will stop!

**Comment by rarkins** [comment]
> Is there any way to limit number of the requests since with this we will have really big load coming to our GitLab?

You can use `prHourlLimit` to limit how many PRs created per hour per repo.

> Logically I was thinking that since we have `schedulerCron` setup it will generate up to 5 PR's on each Renovate Run per schedule.

No, that only controls how often the job queue is replenished

> Additionally if I downgrade renovate to 1.3.1 version the behavior of creating lot of PR's will stop!

- Renovate doesn't and won't support commits per run because it runs permanently
- It is expected that the latest version of Renovate creates more PRs than an 18 month old version
