### ISSUE TITLE
Disabling the execution of scheduled worker jobs when running a separate Webhook server

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-on-prem#239]
I noticed - through beautifying the distributed `src/server.js` - that there's a `global.remediateServerOnly` flag that would allow disabling scheduled workers, only executing webhooks.

Is it possible to configure this via an Environment Variable? 

Likely related to https://github.com/mend/renovate-on-prem/issues/104

My solution right now is to make sure that the `autodiscoverFilter` is unlikely to ever match anything real, but would be handy if there's a better option to use this.

The worker and webhook processes share the same base image, with a built-in `config.js`, so one alternative is that I could bake into the `config.js` the `remediateServerOnly` option?

**Comment by rarkins** [comment]
"Remediate" is Mend's commercial adaptation of Renovate and this setting you found is a commercial-only feature to enable horizontal scalability of workers. We do not plan to support horizontal scalability "natively" in Renovate, but if you're after something simple like "don't do X" which you manage yourself, then I'm not against it.

Is it as simple as you just wanting an instance of Renovate which doesn't run scheduled jobs, and only runs jobs in response to webhooks?

**Comment by jamietanna** [comment]
> Is it as simple as you just wanting an instance of Renovate which doesn't run scheduled jobs, and only runs jobs in response to webhooks?

Yes, exactly.

I _believe_ the codepaths exist in the commercial offering, there just doesn't seem to be a way to configure that via environment variables.

To confirm, I'm using Mend Renovate On-Prem, which runs the Docker image `whitesource/renovate:2.6.0` and is where I found the above `remediateServerOnly` in the JS code distributed as part of that.

**Comment by rarkins** [comment]
That's not the actual code path in the commercial offering either. `remediateServerOnly` means it processes no jobs of its own - scheduled or webhooks.

What if you set a value for `SCHEDULER_CRON` which never executes? e.g. once every 100 years or something like that

**Comment by jamietanna** [comment]
Ah, gotcha. Yes, that works too - I'll do that, thanks!
