### ISSUE TITLE
[Question] MR webhook rebase performance

### ISSUE THREAD

**Issue by buffcode** [mend/renovate-on-prem#240]
We are running `whitesource/renovate:2.6.0` against an on-prem GitLab instance.

When I trigger a rebase via "If you want to rebase/retry this MR, click this checkbox" in the MR, Renovate successfully receives the webhook and starts processing ASAP.

But it seems, as if the task runs not (completely) in the context of the MR, because every dependency of every manager in the project will be checked, fetched (eg. Changelog) and analyzed. In our case almost 4.000 dependencies (mono-repo) which consumes a lot of time for every single dependency update/rebase:

```
INFO: Dependency extraction complete (repository=redacted, baseBranch=master)
      "stats": {
        "managers": {
          "composer": {"fileCount": 166, "depCount": 2132},
          "docker-compose": {"fileCount": 5, "depCount": 13},
          "dockerfile": {"fileCount": 6, "depCount": 7},
          "gitlabci": {"fileCount": 8, "depCount": 35},
          "gitlabci-include": {"fileCount": 1, "depCount": 1},
          "npm": {"fileCount": 82, "depCount": 1795}
        },
        "total": {"fileCount": 268, "depCount": 3983}
      }
```

IMHO it should be sufficient to limit the "dependency-check" phase to the package manager of the MR (to account for conflicts etc.), but it should not be necessary eg. to check and update 1.795 NPM packages because a composer package is to be updated.

Maybe I am missing a configuration option?

Thanks in advance!

**Comment by rarkins** [comment]
Renovate always runs on the full repo

**Comment by buffcode** [comment]
Is there a special reason or is it just not implemented (yet)/planned?

I just dug through the available source and if the webhook code would inject some information about the rebase-request (in order to determine which package/manager needs to be checked), eg. the  `mergeRenovateConfig` function could dynamically [limit the managers](https://docs.renovatebot.com/modules/manager/#limiting-enabled-managers) via 
```json
{
  "enabledManagers": [`<manager from MR>`]
}
```

The subsequent actions would run on the reduced subset of dependencies.

Unfortunately the webhook logic where this information needs to be passed is part of the closed source, otherwise I would offer to create a PR for that.

**Comment by rarkins** [comment]
The short summary is, it's way more complex to get right than you think. If Renovate knows a branch which needs recalculation, it's not straight forward to immediately know which managers/files/packages to limit itself to, and after that it's not straight forward to ensure it doesn't make any mistakes due to incomplete information.

If you're interested in helping move things forward, the majority of code would need to be in the open source repository, so it's better to discuss there. Please create an "Ideas" discussion if so
