### ISSUE TITLE
Confusing repositories mentioned in log lines

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-on-prem#244]
I've just had a run of Renovate that's appeared with the `$.repository` and `$.result.repository` showing different repo names (below is redacted):

```json
{
    "name": "renovate",
    "hostname": "608981d3836b",
    "pid": 16,
    "level": 30,
    "logContext": "S7xzKmQAb",
    "repository": "repo1",
    "result": {
        "task": "enqueue",
        "installationId": 31961664,
        "repository": "definitely-not-repo1",
        "reason": "master-commit"
    },
    "msg": "Event result",
    "time": "2022-12-07T18:00:54.887Z",
    "v": 0
}
```

It was at the time that a scheduled run was going on (from 1800) so could be due to logging context being set and not unset at the time it was processing this other event?

**Comment by rarkins** [comment]
This could happen if the log message is printed at the same time a repository is being processed. Renovate will set log metadata while processing a repo and anything logged at the same time will get the same metadata. Not desirable, but also not worth "fixing"
