### ISSUE TITLE
Handling disk space issues

### ISSUE THREAD

**Issue by jamietanna** [mend/renovate-on-prem#245]
Running on a large organisation (~2100 repos) is leading to running out of disk as part of the scheduled executions, i.e.:

```json
{
    "name": "renovate",
    "hostname": "608981d3836b",
    "pid": 16,
    "level": 50,
    "logContext": "S7xzKmQAb",
    "repository": "...",
    "msg": "Disk space error - skipping",
    "time": "2022-12-07T18:54:58.168Z",
    "v": 0
}
```

This is for a repo where the Docker image has:

```docker
ENV RENOVATE_REPOSITORY_CACHE=enabled
```

What's the best way to handle this? Remove the repository cache? Look at clearing down the cache more regularly i.e. using another process in the Docker container?

**Comment by rarkins** [comment]
Repository cache usually doesn't take that much space. There's an option to push it to S3 but it's unlikely to be your problem.

When this happens it would be best if you work out which directories are consuming the most space.

**Comment by rarkins** [comment]
Please raise a discussion if future questions
