### ISSUE TITLE
Missing GitHub release for v3.0.2

### ISSUE THREAD

**Issue by mikaello** [mend/renovate-on-prem#260]
The docker image with [tag v3.0.2 is published](https://hub.docker.com/layers/whitesource/renovate/3.0.2/images/sha256-c1944fd364ca37b39b3454421c9e1d32085e70a7e6eadde6e34559b175d89ae4?context=explore), but there is no release published for this patch release in https://github.com/mend/renovate-on-prem/releases.

No git tag for v3.0.2 either.

**Comment by rarkins** [comment]
Thanks, fixed
