### ISSUE TITLE
Private Cross Org Permissions

### ISSUE THREAD

**Issue by mcaulifn** [mend/renovate-on-prem#261]
I am attempting to run on-prem against GitHub Enterprise Cloud. I have the app configured and working for anything internal to the org. However, when attempting to access another internal repository as a dependency, access fails. `RENOVATE_TOKEN` is ignored during startup. What would be the appropriate way to allow this?

**Comment by rarkins** [comment]
This runs as a GitHub app and installation tokens from GitHub apps are always single org, so what you're seeing is expected.

You could provision a PAT in hostRules for the other org

**Comment by mcaulifn** [comment]
That seems to work. It might be worth putting this in the docs as I can see this coming up more when using GHEC.
