### ISSUE TITLE
Request for update to Renovate OSS 34.154.3

### ISSUE THREAD

**Issue by k-jingyang** [mend/renovate-on-prem#262]
Hello, we're facing an issue with renovate-on-prem that is solved with the merged PR,  https://github.com/renovatebot/renovate/pull/20658.

Could renovate-on-prem be released to include Renovate OSS 34.154.3 please? Thank you! :smile:

**Comment by rarkins** [comment]
Updated as part of [3.1.0](https://github.com/mend/renovate-on-prem/releases/tag/3.1.0)
