### ISSUE TITLE
Renovate onboarding do not start

### ISSUE THREAD

**Issue by samaarah** [mend/renovate-on-prem#267]
Hi anyone? 

I have setup renovate kubernetes deployment ok, use GitHub with Github app authentication. Getting repos from renovate logs, using autodiscover, double check Github App permissions.

Should renovate onboarding start when i add new repo? Worked yesterday with docker files, after setting gitprivatekey and renovate encryptionkey, but now not working tested this with 3.0.0 and 4.0.0 versions also. Trace and debug logs do not show any errors???

**Comment by rarkins** [comment]
It's unfortunately not possible to identify any problem based on the description given

**Comment by samaarah** [comment]
Ok. Your are right. Here is more details.

Kubernetes deployment: 
containers:
        - name: whitesource-renovate
          image: "whitesource/renovate:4.0.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "trace"
            - name: ACCEPT_WHITESOURCE_TOS
              value: "y"
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: renovate-env
                  key: github_app_id
            - name: GITHUB_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: renovate-env
                  key: github_app_key
            - name: RENOVATE_PLATFORM
              value: "github"
            - name: SCHEDULER_CRON
              value: "5 * * * *"
            - name: RENOVATE_ENDPOINT
              value: "https://api.github.com"
            - name: LICENSE_KEY
              value: <LICENSE_:KEY> 
           - name: RENOVATE_AUTODISCOVER
              value: "true"
            - name: RENOVATE_ONBOARDING
              value: "true"
              
              
GitHub App configured according to instructions. Renovate logs shows following:


 INFO: Repository count=3
 INFO: Using cron schedule: 5 * * * *
DEBUG: Current datetime = Thu Apr 06 2023 15:19:59 GMT+0000 (Coordinated Universal Time)
 INFO: Job scheduler started
DEBUG: Starting worker
DEBUG: User agent = WhiteSource Renovate
DEBUG: Starting webhook listener
DEBUG: Initialized GitHub webhook handler
DEBUG: No job - sleeping 5s
 INFO: Server bound to port 8080
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s
DEBUG: No job - sleeping 5s

**Comment by samaarah** [comment]
So looks like repos are correctly fetched and do not see any errors from trace logs, but some reason repository onboarding not starting, I can add more repos to Github app side and those will be visible at renovate logs when restarting pod.

**Comment by rarkins** [comment]
According to your config jobs will be enqueued 5 minutes past each hour

**Comment by samaarah** [comment]
Ok. So i have to wait hour to get onboarding running? Just looked those repos and actually get one onboarding now, but two repos are missing that. 🤔

**Comment by rarkins** [comment]
It's controlled by the cron schedule. You can set it to whether you want
