### ISSUE TITLE
Improve logging for tools like Datadog

### ISSUE THREAD

**Issue by dennisameling** [mend/renovate-on-prem#301]
We've been successfully running Renovate on-prem for a couple weeks now. We have Renovate running in an AWS ECS container and logs are being written to Datadog.

The current log format is a bit hard to work with. As you can see in the screenshot below, every line of JSON objects is parsed as a separate log line, which is far from ideal. [Datadog recommends using the Winston library for logging in JSON format](https://docs.datadoghq.com/logs/log_collection/nodejs/?tab=winston30).

Would it be possible to create some environment variable (e.g. `LOGGING_TYPE`) with options like `console` (current setup I think?) and `json`? That'd make it much easier for Datadog to parse those logs.

Thanks in advance!

<img width="1091" alt="Screenshot 2023-07-27 at 10 43 45" src="https://github.com/mend/renovate-on-prem/assets/17739158/d404f7d9-5437-46b6-91a2-20baa51737e2">

**Comment by rarkins** [comment]
You can configure LOG_FORMAT=json in env
