### ISSUE TITLE
[NuGet] Consider projects target framework vs supported frameworks in the package

### ISSUE THREAD

**Issue by SierraNL** [mend/renovate-on-prem#320]
Since more and more NuGet package are dropping support for .Net Framework, I'm starting to get package updates from Renovate that are not applicable for my .Net Framework projects.

If you look at the [HtmlTags](https://www.nuget.org/packages/HtmlTags) package, the current version (9.0.0) only supports net6.0, so no .Net framework. The last version that did support .Net Framework was 7.0.0, but 8.0.0 also still supported .Net Standard 2.0.

So I would not expect a Renovate PR to update to version 9, but only to 8 (since .Net Standard 2.0 is compatible with .Net Framework).
But it appears Renovate just looks at version numbers and not at supported frameworks.

**Comment by rarkins** [comment]
Please start a discussion in https://github.com/renovatebot/renovate as this topic relates to the open source Renovate capabilities and not Renovate On-Prem specifically
